//! Geospatial helpers: NYC neighborhood detection + distance math.
//!
//! Pure functions only — no SpacetimeDB types — so this module is trivially
//! unit-testable with plain `cargo test`.

/// NYC neighborhood bounding boxes: (name, min_lat, max_lat, min_lng, max_lng).
///
/// IMPORTANT: keep this list byte-for-byte in sync with `get_neighborhood()` in
/// the legacy `backend/main.py`. Both must agree so events generated by either
/// path label identically.
pub const NEIGHBORHOODS: &[(&str, f64, f64, f64, f64)] = &[
    ("East Village", 40.7200, 40.7350, -73.9950, -73.9750),
    ("West Village", 40.7280, 40.7400, -74.0100, -73.9950),
    ("SoHo", 40.7180, 40.7280, -74.0050, -73.9900),
    ("Williamsburg", 40.7050, 40.7250, -73.9700, -73.9350),
    ("Bushwick", 40.6850, 40.7100, -73.9350, -73.9050),
    ("Lower East Side", 40.7100, 40.7220, -73.9900, -73.9750),
    ("Chelsea", 40.7400, 40.7550, -74.0100, -73.9900),
    ("Midtown", 40.7480, 40.7650, -74.0000, -73.9700),
    ("Times Square", 40.7550, 40.7620, -73.9900, -73.9820),
    ("Brooklyn Heights", 40.6880, 40.7020, -74.0050, -73.9850),
    ("DUMBO", 40.7000, 40.7080, -73.9950, -73.9800),
    ("Greenpoint", 40.7250, 40.7450, -73.9600, -73.9350),
];

/// Return the neighborhood containing `(lat, lng)`, or `"NYC"` if none match.
pub fn detect_neighborhood(lat: f64, lng: f64) -> String {
    for (name, min_lat, max_lat, min_lng, max_lng) in NEIGHBORHOODS {
        if lat >= *min_lat && lat <= *max_lat && lng >= *min_lng && lng <= *max_lng {
            return (*name).to_string();
        }
    }
    "NYC".to_string()
}

/// Great-circle distance in meters between two lat/lng points (Haversine).
pub fn haversine_meters(lat1: f64, lng1: f64, lat2: f64, lng2: f64) -> f64 {
    const R: f64 = 6_371_000.0; // Earth radius, meters
    let (p1, p2) = (lat1.to_radians(), lat2.to_radians());
    let dphi = (lat2 - lat1).to_radians();
    let dlambda = (lng2 - lng1).to_radians();
    let a = (dphi / 2.0).sin().powi(2) + p1.cos() * p2.cos() * (dlambda / 2.0).sin().powi(2);
    2.0 * R * a.sqrt().asin()
}

/// Human-readable time-of-day bucket used to name events.
pub fn time_of_day(hour_utc_local: u32) -> &'static str {
    match hour_utc_local {
        5..=11 => "Morning",
        12..=16 => "Afternoon",
        17..=20 => "Evening",
        _ => "Night",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_known_neighborhoods() {
        assert_eq!(detect_neighborhood(40.727, -73.985), "East Village");
        assert_eq!(detect_neighborhood(40.715, -73.955), "Williamsburg");
    }

    #[test]
    fn unknown_falls_back_to_nyc() {
        assert_eq!(detect_neighborhood(40.9, -74.3), "NYC");
    }

    #[test]
    fn haversine_is_reasonable() {
        // East Village -> Times Square is roughly 3.2 km.
        let d = haversine_meters(40.7265, -73.9815, 40.7580, -73.9855);
        assert!((d - 3500.0).abs() < 800.0, "got {d} m");
    }
}
