// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  centerLat: __t.f64().name("center_lat"),
  centerLng: __t.f64().name("center_lng"),
  radiusMeters: __t.f64().name("radius_meters"),
  startTime: __t.timestamp().name("start_time"),
  endTime: __t.timestamp().name("end_time"),
  postCount: __t.u32().name("post_count"),
  heatScore: __t.f64().name("heat_score"),
  neighborhood: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
});
