// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.identity().name("user_id"),
  mediaUrl: __t.string().name("media_url"),
  thumbnailUrl: __t.option(__t.string()).name("thumbnail_url"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  timestamp: __t.timestamp(),
  caption: __t.option(__t.string()),
  neighborhood: __t.option(__t.string()),
  eventId: __t.option(__t.u64()).name("event_id"),
  visibility: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
