// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ClusteringSchedule = __t.object("ClusteringSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ClusteringSchedule = __Infer<typeof ClusteringSchedule>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  userId: __t.identity(),
  postId: __t.u64(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type Comment = __Infer<typeof Comment>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  name: __t.string(),
  centerLat: __t.f64(),
  centerLng: __t.f64(),
  radiusMeters: __t.f64(),
  startTime: __t.timestamp(),
  endTime: __t.timestamp(),
  postCount: __t.u32(),
  heatScore: __t.f64(),
  neighborhood: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Follow = __t.object("Follow", {
  id: __t.u64(),
  followerId: __t.identity(),
  followingId: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Follow = __Infer<typeof Follow>;

export const Like = __t.object("Like", {
  id: __t.u64(),
  userId: __t.identity(),
  postId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Like = __Infer<typeof Like>;

export const Post = __t.object("Post", {
  id: __t.u64(),
  userId: __t.identity(),
  mediaUrl: __t.string(),
  thumbnailUrl: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  timestamp: __t.timestamp(),
  caption: __t.option(__t.string()),
  neighborhood: __t.option(__t.string()),
  eventId: __t.option(__t.u64()),
  visibility: __t.string(),
  createdAt: __t.timestamp(),
});
export type Post = __Infer<typeof Post>;

export const User = __t.object("User", {
  id: __t.identity(),
  username: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

