// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import CreatePostReducer from "../create_post_reducer";
import DeleteCommentReducer from "../delete_comment_reducer";
import DeletePostReducer from "../delete_post_reducer";
import FollowUserReducer from "../follow_user_reducer";
import LikePostReducer from "../like_post_reducer";
import SetPostVisibilityReducer from "../set_post_visibility_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetThumbnailReducer from "../set_thumbnail_reducer";
import UnfollowUserReducer from "../unfollow_user_reducer";
import UnlikePostReducer from "../unlike_post_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type CreatePostParams = __Infer<typeof CreatePostReducer>;
export type DeleteCommentParams = __Infer<typeof DeleteCommentReducer>;
export type DeletePostParams = __Infer<typeof DeletePostReducer>;
export type FollowUserParams = __Infer<typeof FollowUserReducer>;
export type LikePostParams = __Infer<typeof LikePostReducer>;
export type SetPostVisibilityParams = __Infer<typeof SetPostVisibilityReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetThumbnailParams = __Infer<typeof SetThumbnailReducer>;
export type UnfollowUserParams = __Infer<typeof UnfollowUserReducer>;
export type UnlikePostParams = __Infer<typeof UnlikePostReducer>;

